on:
  push:
    tags:
      - 'v*'
name: Publish Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install
      - run: yarn package --publish=always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
